{{- if .Values.externalSecrets.enabled -}}
{{- $root := . -}}
{{- range $index, $secret := .Values.externalSecrets.secrets }}
{{- if ne $secret.enabled false }}
---
apiVersion: {{ $root.Values.externalSecrets.apiVersion }}
kind: ExternalSecret
metadata:
  name: {{ default (printf "%s-%d" (include "ora-microservice.fullname" $root) $index) $secret.name }}
  namespace: {{ default $root.Release.Namespace $secret.namespace }}
  labels:
    {{- include "ora-microservice.labels" $root | nindent 4 }}
    {{- with $secret.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  refreshInterval: {{ $secret.refreshInterval | default "1h" }}
  {{- with $secret.secretStoreRef }}
  secretStoreRef:
    name: {{ .name }}
    kind: {{ .kind | default "ClusterSecretStore" }}
  {{- end }}
  {{- with $secret.target }}
  target:
    name: {{ .name | default (default (printf "%s-%d" (include "ora-microservice.fullname" $root) $index) $secret.name) }}
    {{- with .creationPolicy }}
    creationPolicy: {{ . }}
    {{- end }}
    {{- with .deletionPolicy }}
    deletionPolicy: {{ . }}
    {{- end }}
    {{- with .template }}
    template:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- else }}
  target:
    name: {{ default (printf "%s-%d" (include "ora-microservice.fullname" $root) $index) $secret.name }}
    creationPolicy: Owner
  {{- end }}
  {{- with $secret.data }}
  data:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $secret.dataFrom }}
  dataFrom:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
